# Generated by Django 2.2.4 on 2020-11-09 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvshows',
            name='reDate',
            field=models.DateField(),
        ),
    ]
