# Generated by Django 2.2.4 on 2020-11-12 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='postComment',
        ),
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.Comment'),
            preserve_default=False,
        ),
    ]
